name: Build and Deploy site
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Emacs
      uses: dawidd6/action-install-emacs@v3
      with:
        emacs-version: '29.1'
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'extended'
    - name: Run Emacs batch: install ox-hugo & export
      env:
        EMACS_BATCH: "1"
      run: |
        emacs -Q --batch -l .emacs-bootstrap.el
    - name: Build site with Hugo
      run: |
        hugo --source hugo-site --destination public --minify
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
